---
openapi: 3.0.0
info:
  title: LegendaryPokemon
  description: A simple service to check if a pokemon is legendary or not
  termsOfService: http://swagger.io/terms/
  contact:
    name: Cloudmesh REST Service Example
  license:
    name: Apache
  version: 0.0-oas3
servers:
- url: http://localhost:8080
paths:
  /classification/{id}:
    get:
      tags:
      - LEGENDARYCLASSIFY
      description: Returns if a pokemon is legendary based on the input
      operationId: virtualService.classify
      parameters:
      - name: id
        in: path
        required: true
        style: simple
        explode: true
        schema:
          minItems: 1
          type: array
          items:
            type: number
      responses:
        "200":
          description: A binary classification (true or false)
          content:
            application/json:
              schema:
                type: boolean
components: {}
